### PR TITLE
Fix dependencies to `six`

### PR DESCRIPTION
**Pull request by calve**
Also move the `__version__` variable in a separate file to dogde
ImportError in `setup.py`

### CODE REVIEW

**Comment by bnlucas** [comment]
Thanks for this!

**Comment by calve** [comment]
Thanks for merging it that quick !
Would you mind bumping the version and updating the pypi package ?

**Comment by bnlucas** [comment]
I have pushed this to PyPi under the version 3.0.4 as there was already a 3.0.3 for some reason. https://pypi.python.org/pypi/BaseHash/3.0.4

**Comment by calve** [comment]
Thanks a lot.

**Pull request merged**
